import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children, params: {locale}
                                   }: Readonly<{
    children: React.ReactNode;
    params: {locale: string};
}>) {
    return (

        <html>
        <head>
            {/*<link rel="stylesheet" href="../../../static/plugin/bootstrap.min.css"/>*/}
            {/*<link rel="stylesheet" href="../../../static/plugin/style.css"/>*/}
            {/*<link rel="stylesheet" href="../../../static/plugin/themify-icons.css"/>*/}
            {/*<link rel="stylesheet" href="../../../static/plugin/owl.carousel.min.css"/>*/}
            {/*<link rel="stylesheet" href="../../../static/plugin/magnific-popup.css"/>*/}
            {/*<link rel="stylesheet" href="../../../static/plugin/master.css"/>*/}
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
                  rel="stylesheet"/>
            <link rel="stylesheet" href="../../../static/css/bootstrap.min.css"/>
            <link rel="stylesheet" href="../../../static/css/style.css"/>

        </head>
        <body className={inter.className}>
        {/*<NextIntlClientProvider locale={locale} messages={messages}>*/}
        {children}
        {/*</NextIntlClientProvider>*/}
        </body>
        </html>
    );
}
